/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package setu.mad1.interfaces

import java.util.*

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val dataStoreFactory = DataStoreFactory()
    val dataStore = dataStoreFactory.create("json")
    dataStore.write(Task("get a life", Date()))
    println(dataStore is JsonDataStore)
    println(dataStore is Datastore)
    println(dataStore is Runnable)
}
